services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: nadyavalin/library-app:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
      - DATABASE_USER=library_user
      - DATABASE_PASSWORD=library_password
      - DATABASE_NAME=home_library
      - PORT=4000
      - CRYPT_SALT=10
      - JWT_SECRET_KEY=secret123123
      - JWT_SECRET_REFRESH_KEY=secret123123
      - TOKEN_EXPIRE_TIME=1h
      - TOKEN_REFRESH_EXPIRE_TIME=24h
    depends_on:
      - db
    networks:
      - library-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: nadyavalin/library-db:latest
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    networks:
      - library-network
    restart: unless-stopped

networks:
  library-network:
    driver: bridge

volumes:
  pgdata:
