FROM postgres:16

ENV POSTGRES_USER=library_user
ENV POSTGRES_PASSWORD=library_password
ENV POSTGRES_DB=home_library

COPY db/postgresql.conf /etc/postgresql/postgresql.conf

EXPOSE 5433

VOLUME /var/lib/postgresql/data

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]