services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: nadyavalin/library-app:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=library_user
      - DATABASE_PASSWORD=library_password
      - DATABASE_NAME=home_library
    depends_on:
      db:
        condition: service_healthy
    networks:
      - library-network
    restart: unless-stopped

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
      - POSTGRES_DB=home_library
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U library_user -d home_library" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - library-network
    restart: unless-stopped

networks:
  library-network:
    name: library-network
    driver: bridge

volumes:
  pgdata:
